name: PlatformIO CI
on: [workflow_call, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - variant: actuators_arduino_json_8266
            example: examples/arduino/actuators
            board: d1_mini
            extra_dependencies: "johboh/MQTTRemote8266@^6.0.2, bblanchon/ArduinoJson@^7.1.0"
          - variant: sensors_arduino_json_8266
            example: examples/arduino/sensors
            board: d1_mini
            extra_dependencies: "johboh/MQTTRemote8266@^6.0.2, bblanchon/ArduinoJson@^7.1.0"
          - variant: actuators_arduino_json
            example: examples/arduino/actuators
            board: lolin_s2_mini
            extra_dependencies: "johboh/MQTTRemote@^6.0.2, bblanchon/ArduinoJson@^7.1.0"
          - variant: actuators_nlohmann_json
            example: examples/arduino/actuators
            board: lolin_c3_mini
            extra_dependencies: "johboh/MQTTRemote@^6.0.2, johboh/nlohmann-json@^3.12.0"
          - variant: sensors_arduino_json
            example: examples/arduino/sensors
            board: lolin_s2_mini
            extra_dependencies: "johboh/MQTTRemote@^6.0.2, bblanchon/ArduinoJson@^7.1.0"
          - variant: sensors_nlohmann_json
            example: examples/arduino/sensors
            board: lolin_c3_mini
            extra_dependencies: "johboh/MQTTRemote@^6.0.2, johboh/nlohmann-json@^3.12.0"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO targets
        run: ${{ env.PLATFORMIO_CI_BASE_CMD }} --project-option="lib_deps=${{ matrix.target.extra_dependencies }}"
        env:
          PLATFORMIO_CI_BASE_CMD: pio ci --lib="." --board=${{ matrix.target.board }} --project-option="build_unflags=-std=gnu++11" --project-option="build_flags=-std=gnu++17" --project-option="lib_ldf_mode=deep"
          PLATFORMIO_CI_SRC: ${{ matrix.target.example }}
