name: PlatformIO CI
on: [workflow_call, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - variant: actuators_arduino_json
            example: examples/arduino/actuators
            extra_dependencies: "johboh/MQTTRemote@^4.0.4, bblanchon/ArduinoJson@^7.1.0"
          - variant: actuators_nlohmann_json
            example: examples/arduino/actuators
            extra_dependencies: "johboh/MQTTRemote@^4.0.4, johboh/nlohmann-json@^3.11.3"
          - variant: sensors_arduino_json
            example: examples/arduino/sensors
            extra_dependencies: "johboh/MQTTRemote@^4.0.4, bblanchon/ArduinoJson@^7.1.0"
          - variant: sensors_nlohmann_json
            example: examples/arduino/sensors
            extra_dependencies: "johboh/MQTTRemote@^4.0.4, johboh/nlohmann-json@^3.11.3"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO targets
        run: ${{ env.PLATFORMIO_CI_BASE_CMD }} --project-option="lib_deps=${{ matrix.target.extra_dependencies }}"
        env:
          PLATFORMIO_CI_BASE_CMD: pio ci --lib="." --board=lolin_s2_mini --board=lolin_c3_mini --board="d1_mini" --project-option="build_unflags=-std=gnu++11" --project-option="build_flags=-std=gnu++17" --project-option="platform=espressif32@6.4.0" --project-option="lib_ldf_mode=deep"
          PLATFORMIO_CI_SRC: ${{ matrix.target.example }}
